Skeleton\Kernel\Domain\Model\StoredEvent:
  type: entity
  table: event
  id:
    id:
      type: string
  fields:
    eventBody:
      type: text
    typeName:
      type: string
      length: 255
    occurredOn:
      type: datetime