Skeleton\BasketTeam\Domain\BasketTeam\Model\Aggregate\PlayerState:
    type: entity
    table: player
    indexes:
        number_index:
            columns: [ number ]
        team_index:
            columns: [team_id]
    id:
        teamId:
            type: string
        number:
            type: integer
            length: 2
    fields:
        name:
            type: string
            length: 100
        averageRating:
            type: float
            length: 3
        role:
            type: string
            length: 50
